// <auto-generated />
using System;
using Exercices_Formulaire_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercices_Formulaire_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211221957_ChangementDoubleToFloat")]
    partial class ChangementDoubleToFloat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<bool>("EstEnEmploi")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaysId")
                        .HasColumnType("int");

                    b.Property<float>("SalaireAnnuel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("PaysId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Pays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Afghanistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Albanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Antarctique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Algérie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Samoa Américaines",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Andorre",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Angola",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Antigua-et-Barbuda",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 9,
                            Nom = "Azerbaïdjan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 10,
                            Nom = "Argentine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 11,
                            Nom = "Australie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 12,
                            Nom = "Autriche",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 13,
                            Nom = "Bahamas",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 14,
                            Nom = "Bahreïn",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 15,
                            Nom = "Bangladesh",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 16,
                            Nom = "Arménie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 17,
                            Nom = "Barbade",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 18,
                            Nom = "Belgique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 19,
                            Nom = "Bermudes",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 20,
                            Nom = "Bhoutan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 21,
                            Nom = "Bolivie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 22,
                            Nom = "Bosnie-Herzégovine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 23,
                            Nom = "Botswana",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 24,
                            Nom = "Île Bouvet",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 25,
                            Nom = "Brésil",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 26,
                            Nom = "Belize",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 27,
                            Nom = "Territoire Britannique de l'Océan Indien",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 28,
                            Nom = "Îles Salomon",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 29,
                            Nom = "Îles Vierges Britanniques",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 30,
                            Nom = "Brunéi Darussalam",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 31,
                            Nom = "Bulgarie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 32,
                            Nom = "Myanmar",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 33,
                            Nom = "Burundi",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 34,
                            Nom = "Bélarus",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 35,
                            Nom = "Cambodge",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 36,
                            Nom = "Cameroun",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 37,
                            Nom = "Canada",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 38,
                            Nom = "Cap-vert",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 39,
                            Nom = "Îles Caïmanes",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 40,
                            Nom = "République Centrafricaine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 41,
                            Nom = "Sri Lanka",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 42,
                            Nom = "Tchad",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 43,
                            Nom = "Chili",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 44,
                            Nom = "Chine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 45,
                            Nom = "Taïwan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 46,
                            Nom = "Île Christmas",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 47,
                            Nom = "Îles Cocos (Keeling)",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 48,
                            Nom = "Colombie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 49,
                            Nom = "Comores",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 50,
                            Nom = "Mayotte",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 51,
                            Nom = "République du Congo",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 52,
                            Nom = "République Démocratique du Congo",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 53,
                            Nom = "Îles Cook",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 54,
                            Nom = "Costa Rica",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 55,
                            Nom = "Croatie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 56,
                            Nom = "Cuba",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 57,
                            Nom = "Chypre",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 58,
                            Nom = "République Tchèque",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 59,
                            Nom = "Bénin",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 60,
                            Nom = "Danemark",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 61,
                            Nom = "Dominique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 62,
                            Nom = "République Dominicaine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 63,
                            Nom = "Équateur",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 64,
                            Nom = "El Salvador",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 65,
                            Nom = "Guinée Équatoriale",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 66,
                            Nom = "Éthiopie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 67,
                            Nom = "Érythrée",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 68,
                            Nom = "Estonie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 69,
                            Nom = "Îles Féroé",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 70,
                            Nom = "Îles (malvinas) Falkland",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 71,
                            Nom = "Géorgie du Sud et les Îles Sandwich du Sud",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 72,
                            Nom = "Fidji",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 73,
                            Nom = "Finlande",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 74,
                            Nom = "Îles Åland",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 75,
                            Nom = "France",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 76,
                            Nom = "Guyane Française",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 77,
                            Nom = "Polynésie Française",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 78,
                            Nom = "Terres Australes Françaises",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 79,
                            Nom = "Djibouti",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 80,
                            Nom = "Gabon",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 81,
                            Nom = "Géorgie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 82,
                            Nom = "Gambie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 83,
                            Nom = "Territoire Palestinien Occupé",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 84,
                            Nom = "Allemagne",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 85,
                            Nom = "Ghana",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 86,
                            Nom = "Gibraltar",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 87,
                            Nom = "Kiribati",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 88,
                            Nom = "Grèce",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 89,
                            Nom = "Groenland",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 90,
                            Nom = "Grenade",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 91,
                            Nom = "Guadeloupe",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 92,
                            Nom = "Guam",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 93,
                            Nom = "Guatemala",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 94,
                            Nom = "Guinée",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 95,
                            Nom = "Guyana",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 96,
                            Nom = "Haïti",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 97,
                            Nom = "Îles Heard et Mcdonald",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 98,
                            Nom = "Saint-Siège (état de la Cité du Vatican)",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 99,
                            Nom = "Honduras",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 100,
                            Nom = "Hong-Kong",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 101,
                            Nom = "Hongrie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 102,
                            Nom = "Islande",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 103,
                            Nom = "Inde",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 104,
                            Nom = "Indonésie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 105,
                            Nom = "République Islamique d'Iran",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 106,
                            Nom = "Iraq",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 107,
                            Nom = "Irlande",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 108,
                            Nom = "Israël",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 109,
                            Nom = "Italie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 110,
                            Nom = "Côte d'Ivoire",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 111,
                            Nom = "Jamaïque",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 112,
                            Nom = "Japon",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 113,
                            Nom = "Kazakhstan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 114,
                            Nom = "Jordanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 115,
                            Nom = "Kenya",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 116,
                            Nom = "République Populaire Démocratique de Corée",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 117,
                            Nom = "République de Corée",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 118,
                            Nom = "Koweït",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 119,
                            Nom = "Kirghizistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 120,
                            Nom = "République Démocratique Populaire Lao",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 121,
                            Nom = "Liban",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 122,
                            Nom = "Lesotho",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 123,
                            Nom = "Lettonie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 124,
                            Nom = "Libéria",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 125,
                            Nom = "Jamahiriya Arabe Libyenne",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 126,
                            Nom = "Liechtenstein",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 127,
                            Nom = "Lituanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 128,
                            Nom = "Luxembourg",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 129,
                            Nom = "Macao",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 130,
                            Nom = "Madagascar",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 131,
                            Nom = "Malawi",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 132,
                            Nom = "Malaisie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 133,
                            Nom = "Maldives",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 134,
                            Nom = "Mali",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 135,
                            Nom = "Malte",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 136,
                            Nom = "Martinique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 137,
                            Nom = "Mauritanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 138,
                            Nom = "Maurice",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 139,
                            Nom = "Mexique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 140,
                            Nom = "Monaco",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 141,
                            Nom = "Mongolie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 142,
                            Nom = "République de Moldova",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 143,
                            Nom = "Montserrat",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 144,
                            Nom = "Maroc",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 145,
                            Nom = "Mozambique",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 146,
                            Nom = "Oman",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 147,
                            Nom = "Namibie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 148,
                            Nom = "Nauru",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 149,
                            Nom = "Népal",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 150,
                            Nom = "Pays-Bas",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 151,
                            Nom = "Antilles Néerlandaises",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 152,
                            Nom = "Aruba",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 153,
                            Nom = "Nouvelle-Calédonie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 154,
                            Nom = "Vanuatu",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 155,
                            Nom = "Nouvelle-Zélande",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 156,
                            Nom = "Nicaragua",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 157,
                            Nom = "Niger",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 158,
                            Nom = "Nigéria",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 159,
                            Nom = "Niué",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 160,
                            Nom = "Île Norfolk",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 161,
                            Nom = "Norvège",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 162,
                            Nom = "Îles Mariannes du Nord",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 163,
                            Nom = "Îles Mineures Éloignées des États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 164,
                            Nom = "États Fédérés de Micronésie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 165,
                            Nom = "Îles Marshall",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 166,
                            Nom = "Palaos",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 167,
                            Nom = "Pakistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 168,
                            Nom = "Panama",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 169,
                            Nom = "Papouasie-Nouvelle-Guinée",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 170,
                            Nom = "Paraguay",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 171,
                            Nom = "Pérou",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 172,
                            Nom = "Philippines",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 173,
                            Nom = "Pitcairn",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 174,
                            Nom = "Pologne",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 175,
                            Nom = "Portugal",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 176,
                            Nom = "Guinée-Bissau",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 177,
                            Nom = "Timor-Leste",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 178,
                            Nom = "Porto Rico",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 179,
                            Nom = "Qatar",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 180,
                            Nom = "Réunion",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 181,
                            Nom = "Roumanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 182,
                            Nom = "Fédération de Russie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 183,
                            Nom = "Rwanda",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 184,
                            Nom = "Sainte-Hélène",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 185,
                            Nom = "Saint-Kitts-et-Nevis",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 186,
                            Nom = "Anguilla",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 187,
                            Nom = "Sainte-Lucie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 188,
                            Nom = "Saint-Pierre-et-Miquelon",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 189,
                            Nom = "Saint-Vincent-et-les Grenadines",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 190,
                            Nom = "Saint-Marin",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 191,
                            Nom = "Sao Tomé-et-Principe",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 192,
                            Nom = "Arabie Saoudite",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 193,
                            Nom = "Sénégal",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 194,
                            Nom = "Seychelles",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 195,
                            Nom = "Sierra Leone",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 196,
                            Nom = "Singapour",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 197,
                            Nom = "Slovaquie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 198,
                            Nom = "Viet Nam",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 199,
                            Nom = "Slovénie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 200,
                            Nom = "Somalie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 201,
                            Nom = "Afrique du Sud",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 202,
                            Nom = "Zimbabwe",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 203,
                            Nom = "Espagne",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 204,
                            Nom = "Sahara Occidental",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 205,
                            Nom = "Soudan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 206,
                            Nom = "Suriname",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 207,
                            Nom = "Svalbard etÎle Jan Mayen",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 208,
                            Nom = "Swaziland",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 209,
                            Nom = "Suède",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 210,
                            Nom = "Suisse",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 211,
                            Nom = "République Arabe Syrienne",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 212,
                            Nom = "Tadjikistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 213,
                            Nom = "Thaïlande",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 214,
                            Nom = "Togo",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 215,
                            Nom = "Tokelau",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 216,
                            Nom = "Tonga",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 217,
                            Nom = "Trinité-et-Tobago",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 218,
                            Nom = "Émirats Arabes Unis",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 219,
                            Nom = "Tunisie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 220,
                            Nom = "Turquie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 221,
                            Nom = "Turkménistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 222,
                            Nom = "Îles Turks et Caïques",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 223,
                            Nom = "Tuvalu",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 224,
                            Nom = "Ouganda",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 225,
                            Nom = "Ukraine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 226,
                            Nom = "L'ex-République Yougoslave de Macédoine",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 227,
                            Nom = "Égypte",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 228,
                            Nom = "Royaume-Uni",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 229,
                            Nom = "Île de Man",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 230,
                            Nom = "République-Unie de Tanzanie",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 231,
                            Nom = "États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 232,
                            Nom = "Îles Vierges des États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 233,
                            Nom = "Burkina Faso",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 234,
                            Nom = "Uruguay",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 235,
                            Nom = "Ouzbékistan",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 236,
                            Nom = "Venezuela",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 237,
                            Nom = "Wallis et Futuna",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 238,
                            Nom = "Samoa",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 239,
                            Nom = "Yémen",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 240,
                            Nom = "Serbie-et-Monténégro",
                            Superficie = 0
                        },
                        new
                        {
                            Id = 241,
                            Nom = "Zambie",
                            Superficie = 0
                        });
                });

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Employe", b =>
                {
                    b.HasOne("Exercices_Formulaire_Web.Models.Departement", "Departement")
                        .WithMany("Employes")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercices_Formulaire_Web.Models.Pays", "PaysOrigine")
                        .WithMany("Employes")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("PaysOrigine");
                });

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Departement", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("Exercices_Formulaire_Web.Models.Pays", b =>
                {
                    b.Navigation("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
